// Shared chat styles — extracted from ChatView.jsx for Sprint 97 refacto.
// Keeping the original object verbatim to preserve the exact visual rendering.

export const s = {
  root: { display: 'flex', height: '100%', overflow: 'hidden' },

  // Sessions panel
  panel: (show) => ({
    width: show ? '220px' : '0',
    overflow: 'hidden',
    transition: 'width 0.2s ease',
    flexShrink: 0,
    background: '#111',
    borderRight: '1px solid #222',
    display: 'flex',
    flexDirection: 'column',
  }),
  panelInner: { width: '220px', display: 'flex', flexDirection: 'column', height: '100%' },
  panelHeader: {
    padding: '14px 12px 10px',
    borderBottom: '1px solid #222',
    flexShrink: 0,
  },
  newBtn: {
    width: '100%',
    padding: '8px 12px',
    background: '#7c3aed22',
    border: '1px solid #7c3aed44',
    borderRadius: '8px',
    color: '#a78bfa',
    cursor: 'pointer',
    fontSize: '13px',
    textAlign: 'left',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  searchBox: {
    margin: '8px 8px 4px',
    position: 'relative',
  },
  searchInput: {
    width: '100%',
    padding: '5px 8px 5px 26px',
    background: '#1a1a1a',
    border: '1px solid #2a2a2a',
    borderRadius: '6px',
    color: '#e0e0e0',
    fontSize: '12px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  searchIcon: {
    position: 'absolute',
    left: '7px',
    top: '6px',
    color: '#555',
    fontSize: '13px',
    pointerEvents: 'none',
  },
  storageBar: {
    display: 'flex',
    gap: '4px',
    padding: '8px 8px',
    borderTop: '1px solid #1c1c1c',
    flexShrink: 0,
  },
  storageBtn: (active) => ({
    flex: 1,
    padding: '4px 2px',
    background: active ? '#7c3aed33' : 'transparent',
    border: `1px solid ${active ? '#7c3aed66' : '#222'}`,
    borderRadius: '6px',
    color: active ? '#c4b5fd' : '#555',
    cursor: 'pointer',
    fontSize: '13px',
    textAlign: 'center',
  }),
  snippetText: {
    fontSize: '11px',
    color: '#555',
    marginTop: '2px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  sessionList: { flex: 1, overflowY: 'auto', padding: '8px 6px' },
  sessionItem: (active) => ({
    padding: '8px 10px',
    borderRadius: '6px',
    background: active ? '#7c3aed18' : 'transparent',
    cursor: 'pointer',
    marginBottom: '2px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '6px',
    group: true,
  }),
  sessionTitle: (active) => ({
    fontSize: '13px',
    color: active ? '#c4b5fd' : '#9a9a9a',
    fontWeight: active ? '500' : '400',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    flex: 1,
  }),
  sessionDate: {
    fontSize: '11px',
    color: '#555',
    marginTop: '2px',
    flexShrink: 0,
  },
  deleteBtn: {
    background: 'none',
    border: 'none',
    color: '#555',
    cursor: 'pointer',
    fontSize: '12px',
    padding: '0 2px',
    flexShrink: 0,
    lineHeight: 1,
  },

  // Chat area
  chat: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', position: 'relative' },
  header: {
    padding: '10px 16px',
    borderBottom: '1px solid #1e1e1e',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexShrink: 0,
    background: '#0f0f0f',
  },
  toggleBtn: {
    background: 'none',
    border: '1px solid #2a2a2a',
    borderRadius: '6px',
    color: '#6b6b6b',
    cursor: 'pointer',
    padding: '4px 8px',
    fontSize: '14px',
    lineHeight: 1,
  },
  sessionTitleDisplay: {
    fontSize: '13px',
    color: '#5a5a5a',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  messageList: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px 0 8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  emptyState: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '20px',
    color: '#6b6b6b',
  },
  emptyTitle: { fontSize: '18px', color: '#e8e8e8', fontWeight: '500' },
  suggestions: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap',
    justifyContent: 'center',
    maxWidth: '500px',
  },
  suggestionBtn: {
    padding: '8px 14px',
    border: '1px solid #2a2a2a',
    borderRadius: '20px',
    background: '#1a1a1a',
    color: '#a0a0a0',
    cursor: 'pointer',
    fontSize: '13px',
  },
  msgWrapper: (role) => ({
    display: 'flex',
    justifyContent: role === 'user' ? 'flex-end' : 'flex-start',
    padding: '0 20px',
  }),
  bubble: (role) => ({
    maxWidth: '72%',
    padding: '10px 14px',
    borderRadius: role === 'user' ? '16px 16px 4px 16px' : '16px 16px 16px 4px',
    background: role === 'user' ? '#4c1d95' : '#1e1e1e',
    color: '#e8e8e8',
    fontSize: '14px',
    lineHeight: '1.6',
    border: role === 'user' ? 'none' : '1px solid #2a2a2a',
  }),

  // Tool cards
  toolsWrapper: { marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '4px' },
  toolCard: {
    borderRadius: '6px',
    overflow: 'hidden',
    border: '1px solid #2a2a2a',
    fontSize: '12px',
  },
  toolHeader: (isError, isRunning) => ({
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 8px',
    background: '#161616',
    border: 'none',
    cursor: isRunning ? 'default' : 'pointer',
    textAlign: 'left',
    color: isError ? '#ef4444' : isRunning ? '#9a9a9a' : '#22c55e',
  }),
  toolName: { color: '#b0b0b0', fontFamily: 'monospace', flex: 1 },
  toolChevron: { color: '#555', marginLeft: '4px' },
  toolBody: {
    padding: '8px',
    background: '#111',
    borderTop: '1px solid #222',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  toolLabel: { fontSize: '10px', color: '#555', textTransform: 'uppercase', letterSpacing: '0.05em' },
  toolPre: {
    margin: 0,
    padding: '6px',
    background: '#0a0a0a',
    borderRadius: '4px',
    color: '#9b9b9b',
    fontSize: '11px',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    maxHeight: '160px',
    overflowY: 'auto',
    fontFamily: 'monospace',
  },

  streamingDots: { padding: '10px 20px' },
  inputArea: {
    padding: '12px 20px',
    borderTop: '1px solid #2a2a2a',
    background: '#0f0f0f',
    display: 'flex',
    gap: '10px',
    alignItems: 'flex-end',
  },
  textarea: {
    flex: 1,
    background: '#1a1a1a',
    border: '1px solid #2a2a2a',
    borderRadius: '10px',
    color: '#e8e8e8',
    padding: '10px 14px',
    fontSize: '14px',
    fontFamily: 'inherit',
    resize: 'none',
    outline: 'none',
    minHeight: '42px',
    maxHeight: '120px',
    lineHeight: '1.5',
  },
  sendBtn: (disabled) => ({
    padding: '10px 16px',
    background: disabled ? '#2a2a2a' : '#7c3aed',
    border: 'none',
    borderRadius: '10px',
    color: disabled ? '#6b6b6b' : '#fff',
    cursor: disabled ? 'not-allowed' : 'pointer',
    fontSize: '16px',
    flexShrink: 0,
    height: '42px',
  }),
  peBtn: (active) => ({
    padding: '0 12px',
    height: '42px',
    background: active ? '#7c3aed22' : 'transparent',
    border: `1px solid ${active ? '#7c3aed66' : '#333'}`,
    borderRadius: '10px',
    color: active ? '#a78bfa' : '#555',
    cursor: 'pointer',
    fontSize: '14px',
    flexShrink: 0,
    transition: 'all 0.15s ease',
  }),
  micBtn: (recording) => ({
    width: '42px',
    height: '42px',
    background: recording ? '#ef444422' : 'transparent',
    border: `1px solid ${recording ? '#ef444466' : '#333'}`,
    borderRadius: '10px',
    color: recording ? '#ef4444' : '#555',
    cursor: 'pointer',
    fontSize: '16px',
    flexShrink: 0,
    transition: 'all 0.15s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  }),
  ttsBtn: (active) => ({
    width: '42px',
    height: '42px',
    background: active ? '#0891b222' : 'transparent',
    border: `1px solid ${active ? '#0891b266' : '#333'}`,
    borderRadius: '10px',
    color: active ? '#22d3ee' : '#555',
    cursor: 'pointer',
    fontSize: '15px',
    flexShrink: 0,
    transition: 'all 0.15s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  refinedBadge: {
    display: 'inline-block',
    marginTop: '4px',
    fontSize: '10px',
    color: '#7c3aed99',
    letterSpacing: '0.05em',
  },

  // RAG chip & panel
  ragChip: {
    background: 'none',
    border: 'none',
    color: '#22d3ee',
    cursor: 'pointer',
    fontSize: '11px',
    padding: '2px 4px',
    marginTop: '3px',
    opacity: 0.65,
    display: 'inline-block',
  },
  ragPanel: {
    background: '#161616',
    border: '1px solid #2a2a2a',
    borderRadius: '8px',
    padding: '10px',
    marginTop: '4px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    maxWidth: '360px',
    marginLeft: 'auto',
  },
  ragEntry: {
    fontSize: '12px',
    borderLeft: '2px solid #06b6d444',
    paddingLeft: '8px',
  },
  ragEntryMeta: {
    color: '#22d3ee',
    fontSize: '10px',
    fontWeight: '600',
    marginBottom: '2px',
  },
  ragEntryContent: {
    color: '#9b9b9b',
    lineHeight: '1.5',
    wordBreak: 'break-word',
  },
  ragBtn: (active) => ({
    padding: '0 12px',
    height: '42px',
    background: active ? '#06b6d422' : 'transparent',
    border: `1px solid ${active ? '#06b6d466' : '#333'}`,
    borderRadius: '10px',
    color: active ? '#22d3ee' : '#555',
    cursor: 'pointer',
    fontSize: '14px',
    flexShrink: 0,
    transition: 'all 0.15s ease',
  }),
  summarizeBtn: (active) => ({
    padding: '0 12px',
    height: '42px',
    background: active ? '#059669' + '22' : 'transparent',
    border: `1px solid ${active ? '#059669' + '66' : '#333'}`,
    borderRadius: '10px',
    color: active ? '#34d399' : '#555',
    cursor: 'pointer',
    fontSize: '14px',
    flexShrink: 0,
    transition: 'all 0.15s ease',
  }),
  fileBtn: {
    width: '42px',
    height: '42px',
    background: 'transparent',
    border: '1px solid #333',
    borderRadius: '10px',
    color: '#555',
    cursor: 'pointer',
    fontSize: '16px',
    flexShrink: 0,
    transition: 'all 0.15s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toast: {
    position: 'fixed',
    bottom: '80px',
    right: '20px',
    background: '#1a1a1a',
    border: '1px solid #2a2a2a',
    borderRadius: '8px',
    padding: '10px 14px',
    fontSize: '13px',
    color: '#e8e8e8',
    zIndex: 9999,
    boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
    transition: 'opacity 0.3s ease',
  },
  uploadCard: {
    background: '#161616',
    border: '1px solid #2a2a2a',
    borderRadius: '8px',
    padding: '12px 14px',
    marginTop: '6px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  uploadCardTitle: {
    color: '#c4b5fd',
    fontSize: '13px',
    fontWeight: '500',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  uploadCardSummary: {
    color: '#b0b0b0',
    fontSize: '13px',
    lineHeight: '1.55',
  },
  uploadCardProposal: {
    color: '#9b9b9b',
    fontSize: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    flexWrap: 'wrap',
  },
  uploadCardWing: { color: '#a78bfa', fontWeight: '600' },
  uploadCardActions: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    marginTop: '2px',
  },
  uploadCardBtn: (variant) => ({
    padding: '5px 12px',
    borderRadius: '6px',
    border: variant === 'cancel' ? '1px solid #333' : 'none',
    cursor: 'pointer',
    fontSize: '12px',
    background: variant === 'confirm' ? '#7c3aed' : variant === 'edit' ? '#1a1a1a' : 'transparent',
    color: variant === 'confirm' ? '#fff' : variant === 'edit' ? '#b0b0b0' : '#555',
  }),
  uploadEditRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  uploadSelect: {
    background: '#1a1a1a',
    border: '1px solid #333',
    borderRadius: '6px',
    color: '#e0e0e0',
    padding: '4px 8px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  uploadRoomInput: {
    background: '#1a1a1a',
    border: '1px solid #333',
    borderRadius: '6px',
    color: '#e0e0e0',
    padding: '4px 8px',
    fontSize: '12px',
    flex: 1,
    outline: 'none',
    minWidth: '120px',
  },
  uploadStatusOk: { fontSize: '12px', color: '#22c55e' },
  uploadStatusErr: { fontSize: '12px', color: '#ef4444' },
};

export const IPCRA_WINGS = ['Input', 'Projet', 'Casquette', 'Ressource', 'Archive'];

export const STORAGE_MODES = [
  { value: 'local', icon: '💾', title: 'Local' },
  { value: 'cloud', icon: '☁️', title: 'Cloud' },
  { value: 'mempalace', icon: '🧠', title: 'MemPalace' },
];

export const SUGGESTIONS = [
  'Classer une note',
  'Créer une tâche Forge',
  'Lister mes mondes Oria',
];

export const SLASH_COMMANDS = [
  { cmd: '/search', label: '/search <requête>', desc: 'Chercher dans MemPalace' },
  { cmd: '/save', label: '/save <contenu>', desc: 'Sauvegarder dans MemPalace' },
  { cmd: '/task', label: '/task <titre>', desc: 'Créer une tâche Swarm' },
  { cmd: '/summarize', label: '/summarize', desc: 'Résumer la conversation' },
];

import { relativeDate as sharedRelativeDate, formatBytes } from '@workspace/shared-ui/utils';

export const relativeDate = sharedRelativeDate;
export const formatSize = (bytes) => formatBytes(bytes, { placeholder: '' });

export function stripMarkdownForTTS(text) {
  return text
    .replace(/```[\s\S]*?```/g, '')
    .replace(/`[^`]+`/g, '')
    .replace(/#{1,6}\s+/gm, '')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1')
    .replace(/^[-*+]\s+/gm, '')
    .replace(/^\d+\.\s+/gm, '')
    .replace(/\n{3,}/g, '\n')
    .trim();
}
